### ISSUE TITLE
Newer release?

### ISSUE THREAD

**Issue by wilr** [Level51/silverstripe-jwt-utils#2]
Any chance of getting a release for master?

**Comment by JZubero** [comment]
Could you please briefly explain the intent behind your request?

**Comment by wilr** [comment]
Installing as per the README instructions (0.1.0) installs the pre SilverStripe 4 version. I assume you would need to tag a 0.2.0 release for the latest version.

**Comment by JZubero** [comment]
Fair enough. Just created the new tag.
